### ISSUE TITLE
Ajax observer appears to be broken

### ISSUE THREAD

**Issue by stevelacey** [homerchen19/github-file-icon#72]
The icons load, and stay, on a fresh page load, or a hard refresh / cached page load, but clicking into directory and triggering ajax results in a flash of icons then back to the generic icons.

Tested on Chrome 80.0.3987.106 (Official Build) (64-bit)

**Comment by xxhomey19** [comment]
Hi @stevelacey 

I've tried to fix this issue this afternoon, but it somehow still doesn't work :(
I have referenced some code from https://github.com/sindresorhus/hide-files-on-github/blob/master/source/content.tsx#L103 and https://github.com/sindresorhus/refined-github/blob/master/source/libs/on-file-list-update.ts. However, none of them can solve this issue. Maybe this happens because of changes on the GitHub side.

**Comment by AlexWayfer** [comment]
Also after "Back" button in browser.

**Comment by kidonng** [comment]
[This extension](https://chrome.google.com/webstore/detail/atom-file-icons-web/pljfkbaipkidhmaljaaakibigbcmmpnc) seems to handle it well.

**Comment by homerchen19** [comment]
It seems to be fixed by #76. Big thanks to @sodatea, feel free to reopen this if this still happens.
